{
  'name': 'CI',
  'on': ['push', 'pull_request','workflow_dispatch'],
  'jobs':
    {
      'CI':
        {
          'runs-on': 'windows-latest',
          'steps':
            [
              { 'uses': 'actions/checkout@v2' },
              {
                'name': 'Use .NET Core',
                'uses': 'actions/setup-dotnet@v1',
                'with': { 'dotnet-version': '7.0' },
              },
              { 
                'name': 'Publish',
                'run': 'dotnet publish -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true --configuration Release -p:DebugType=embedded -o build/' 
              },
              

              {
                'name': 'Upload build',
                'uses': 'actions/upload-artifact@v2',
                'with':
                  {
                    'name': 'valetudo-tray-companion',
                    'path': 'build/valetudo-tray-companion.exe',
                  },
              },
            ],
        },
    },
}
